"""empty message

Revision ID: c967a0c1050b
Revises: None
Create Date: 2016-05-15 00:20:16.173328

"""

# revision identifiers, used by Alembic.
revision = 'c967a0c1050b'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rankings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(), nullable=True),
    sa.Column('upload', sa.Boolean(), nullable=True),
    sa.Column('season', sa.String(), nullable=True),
    sa.Column('ranking', postgresql.JSON(), nullable=True),
    sa.Column('data', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rankings')
    ### end Alembic commands ###
