"""empty message

Revision ID: ce3cdbdf67bb
Revises: 92f5309ff463
Create Date: 2016-06-05 16:54:56.459759

"""

# revision identifiers, used by Alembic.
revision = 'ce3cdbdf67bb'
down_revision = '92f5309ff463'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rankings', sa.Column('official', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rankings', 'official')
    ### end Alembic commands ###
